services:
  client:
    container_name: vite-client
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    command: >
      sh -c "npm install && npm run dev"
  server:
    container_name: express-server
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app"
      - "./server/uploaded:/app/uploaded"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db:/data/db
      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_PASSWORD}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/'
      ME_CONFIG_BASICAUTH: false
volumes:
  db:
