services:
  client:
    container_name: vite-client
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    command: >
        sh -c "npm install && npm run dev"
  node_server:
    container_name: express-server
    build:
      context: "./node_server"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./node_server:/app"
      # - "/app/node_modules"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
  database:
    image: mongo
    container_name: mongo-db
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
volumes:
  db:
